[global]
refresh=2
check_update=false

[outputs]
max_processes_display=10

[processlist]
disable=False
disable_stats=cpu_num,cmdline

[containers]
disable=False
all=False
max_name_size=30
disable_stats=command
podman_sock=unix:///run/podman/podman.sock
