package main

import (
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net"
	"net/http"
	"os"
	"os/exec"
	"os/user"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
	"sync"
	"time"
)

const upsOwnedHeader = "# Generated by JustVoxel Management API. Edit UPS settings through JustVoxel.\n"

var upsConfigDir = "/etc/ups"
var upsShutdownPath = "/etc/justvoxel/ups-shutdown.json"
var upsSharingPath = "/etc/justvoxel/ups-sharing.json"
var upsConfigMu sync.Mutex
var upsRPMQuery = func(ctx context.Context, path string) ([]byte, error) {
	return exec.CommandContext(ctx, "/usr/bin/rpm", "-q", "--qf", "%{NAME}\n%{FILEDIGESTALGO}\n[%{FILENAMES}\t%{FILEDIGESTS}\n]", "-f", path).Output()
}
var upsSystemctl = func(ctx context.Context, args ...string) error {
	return exec.CommandContext(ctx, "systemctl", args...).Run()
}
var upsServiceActive = func(ctx context.Context, unit string) bool {
	return exec.CommandContext(ctx, "systemctl", "is-active", "--quiet", unit).Run() == nil
}
var upsSetNUTGroup = func(path string) error {
	group, err := user.LookupGroup("nut")
	if err != nil {
		return err
	}
	gid, err := strconv.Atoi(group.Gid)
	if err != nil {
		return err
	}
	return os.Chown(path, 0, gid)
}

type upsShutdownConfig struct {
	Enabled         bool   `json:"enabled"`
	DelaySeconds    int    `json:"delay_seconds"`
	MonitorUsername string `json:"monitor_username"`
	MonitorPassword string `json:"monitor_password"`
}

type upsSharingConfig struct {
	Enabled        bool   `json:"enabled"`
	ListenAddress  string `json:"listen_address"`
	ListenPort     int    `json:"listen_port"`
	ClientUsername string `json:"client_username"`
	ClientPassword string `json:"client_password"`
}

func strictUPSJSON(data []byte, value any) error {
	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(value); err != nil {
		return err
	}
	if decoder.Decode(new(any)) != io.EOF {
		return errors.New("extra UPS configuration data")
	}
	return nil
}

var upsIdentifier = regexp.MustCompile(`^[A-Za-z0-9_.-]{1,80}$`)
var upsDriver = regexp.MustCompile(`^[A-Za-z0-9_-]{1,80}$`)
var upsDevicePort = regexp.MustCompile(`^[A-Za-z0-9_./:-]{1,256}$`)

func extendUPSSource(source *upsSourceConfig, name, driver, port string) error {
	if name != "" && !upsIdentifier.MatchString(name) {
		return errors.New("UPS name is invalid")
	}
	if source.Mode == "remote" {
		if driver != "" || port != "" {
			return errors.New("remote UPS cannot configure a local driver")
		}
	} else {
		if (driver == "") != (port == "") {
			return errors.New("local UPS driver and port must be supplied together")
		}
		if driver != "" && (!upsDriver.MatchString(driver) || !upsDevicePort.MatchString(port)) {
			return errors.New("local UPS driver or port is invalid")
		}
		if driver != "" && name == "" {
			return errors.New("local UPS name is required with a driver")
		}
	}
	source.UPSName, source.Driver, source.DevicePort = name, driver, port
	return nil
}

func validUPSCredential(user, password string) bool {
	if !upsIdentifier.MatchString(user) || password == "" || len(password) > 256 {
		return false
	}
	for _, r := range password {
		if r < 33 || r > 126 || r == '#' || r == '"' || r == '\\' {
			return false
		}
	}
	return true
}

func readUPSShutdown() (upsShutdownConfig, error) {
	data, err := upsReadFile(upsShutdownPath)
	if errors.Is(err, os.ErrNotExist) {
		return upsShutdownConfig{}, nil
	}
	if err != nil {
		return upsShutdownConfig{}, err
	}
	var config upsShutdownConfig
	if err := strictUPSJSON(data, &config); err != nil {
		return upsShutdownConfig{}, err
	}
	if config.Enabled && (config.DelaySeconds < 1 || config.DelaySeconds > 86400 || !validUPSCredential(config.MonitorUsername, config.MonitorPassword)) {
		return upsShutdownConfig{}, errors.New("invalid UPS shutdown configuration")
	}
	if !config.Enabled && config != (upsShutdownConfig{}) {
		return upsShutdownConfig{}, errors.New("invalid disabled UPS shutdown configuration")
	}
	return config, nil
}

func readUPSSharing() (upsSharingConfig, error) {
	data, err := upsReadFile(upsSharingPath)
	if errors.Is(err, os.ErrNotExist) {
		return upsSharingConfig{}, nil
	}
	if err != nil {
		return upsSharingConfig{}, err
	}
	var config upsSharingConfig
	if err := strictUPSJSON(data, &config); err != nil {
		return upsSharingConfig{}, err
	}
	if config.Enabled && (net.ParseIP(config.ListenAddress) == nil || config.ListenAddress == "127.0.0.1" || config.ListenAddress == "::1" || config.ListenAddress == "0.0.0.0" || config.ListenAddress == "::" || config.ListenPort < 1 || config.ListenPort > 65535 || !validUPSCredential(config.ClientUsername, config.ClientPassword)) {
		return upsSharingConfig{}, errors.New("invalid UPS sharing configuration")
	}
	if !config.Enabled && config != (upsSharingConfig{}) {
		return upsSharingConfig{}, errors.New("invalid disabled UPS sharing configuration")
	}
	return config, nil
}

func writeUPSJSON(path string, value any) error {
	data, err := json.Marshal(value)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		return err
	}
	return atomicWrite(path, append(data, '\n'), 0o600)
}

func stopUPSLocalServices(ctx context.Context) error {
	for _, unit := range []string{"nut.target", "nut-server.service", "nut-driver.target", "nut-driver-enumerator.path", "nut-driver-enumerator.service"} {
		if err := upsSystemctl(ctx, "disable", "--now", unit); err != nil {
			return err
		}
	}
	return nil
}

func saveUPSSource(ctx context.Context, source upsSourceConfig) error {
	upsConfigMu.Lock()
	defer upsConfigMu.Unlock()
	previous, err := readUPSSource()
	if err != nil {
		return err
	}
	shutdown, err := readUPSShutdown()
	if err != nil {
		return err
	}
	sharing, err := readUPSSharing()
	if err != nil {
		return err
	}
	if source != previous {
		shutdown = upsShutdownConfig{}
		sharing = upsSharingConfig{}
	}
	if err := upsSystemctl(ctx, "disable", "--now", "nut-monitor.service"); err != nil {
		return err
	}
	if source != previous && previous.Driver != "" {
		if err := stopUPSLocalServices(ctx); err != nil {
			return err
		}
	}
	if err := renderUPSNative(source, shutdown, sharing); err != nil {
		return err
	}
	if err := writeUPSSource(source); err != nil {
		return err
	}
	if source != previous {
		if err := writeUPSJSON(upsShutdownPath, shutdown); err != nil {
			return err
		}
		if err := writeUPSJSON(upsSharingPath, sharing); err != nil {
			return err
		}
	}
	return reconcileUPSServices(ctx, source, shutdown)
}

func forgetUPSSource(ctx context.Context) error {
	upsConfigMu.Lock()
	defer upsConfigMu.Unlock()
	previous, err := readUPSSource()
	if err != nil {
		return err
	}
	local := upsSourceConfig{Mode: "local"}
	if err := upsSystemctl(ctx, "disable", "--now", "nut-monitor.service"); err != nil {
		return err
	}
	if previous.Driver != "" {
		if err := stopUPSLocalServices(ctx); err != nil {
			return err
		}
	}
	if err := renderUPSNative(local, upsShutdownConfig{}, upsSharingConfig{}); err != nil {
		return err
	}
	if err := writeUPSJSON(upsShutdownPath, upsShutdownConfig{}); err != nil {
		return err
	}
	if err := writeUPSJSON(upsSharingPath, upsSharingConfig{}); err != nil {
		return err
	}
	if err := upsRemoveFile(upsSourcePath); err != nil && !errors.Is(err, os.ErrNotExist) {
		return err
	}
	return reconcileUPSServices(ctx, local, upsShutdownConfig{})
}

func (s *server) upsShutdownSave(w http.ResponseWriter, r *http.Request) {
	actor, ok := s.requireAdministrator(w, r)
	if !ok {
		return
	}
	if available, _, _ := upsCapability(); !available {
		writeError(w, http.StatusConflict, "UPS is unavailable on this JustVoxel variant")
		return
	}
	var request upsShutdownConfig
	if !decodeJSON(w, r, &request) {
		return
	}
	upsConfigMu.Lock()
	defer upsConfigMu.Unlock()
	source, err := readUPSSource()
	if err != nil {
		writeError(w, http.StatusConflict, "UPS source configuration is invalid")
		return
	}
	if request.Enabled {
		if request.DelaySeconds < 1 || request.DelaySeconds > 86400 {
			writeError(w, http.StatusBadRequest, "UPS shutdown delay must be 1 to 86400 seconds")
			return
		}
		if !validUPSCredential(request.MonitorUsername, request.MonitorPassword) {
			writeError(w, http.StatusBadRequest, "UPS monitor credentials are invalid")
			return
		}
		if source.UPSName == "" {
			writeError(w, http.StatusConflict, "Select a UPS name before enabling shutdown protection")
			return
		}
		if source.Mode == "local" && source.Driver == "" {
			writeError(w, http.StatusConflict, "Configure a local NUT driver before enabling shutdown protection")
			return
		}
	} else {
		request = upsShutdownConfig{}
	}
	sharing, err := readUPSSharing()
	if err != nil {
		writeError(w, http.StatusConflict, "UPS sharing configuration is invalid")
		return
	}
	if err := upsSystemctl(r.Context(), "disable", "--now", "nut-monitor.service"); err != nil {
		writeError(w, http.StatusServiceUnavailable, "UPS monitor could not be stopped")
		return
	}
	if err := renderUPSNative(source, request, sharing); err == nil {
		err = writeUPSJSON(upsShutdownPath, request)
	}
	if err == nil {
		err = reconcileUPSServices(r.Context(), source, request)
	}
	if err != nil {
		writeError(w, http.StatusInternalServerError, "UPS shutdown configuration could not be applied")
		return
	}
	if s.store != nil {
		_ = s.store.recordAuditEvent(actor, "ups_shutdown_change", source.Mode, true, fmt.Sprintf("enabled=%t delay_seconds=%d", request.Enabled, request.DelaySeconds))
	}
	ctx, cancel := context.WithTimeout(r.Context(), 8*time.Second)
	defer cancel()
	writeJSON(w, http.StatusOK, collectUPSStatus(ctx))
}

func (s *server) upsSharingSave(w http.ResponseWriter, r *http.Request) {
	actor, ok := s.requireAdministrator(w, r)
	if !ok {
		return
	}
	if available, _, _ := upsCapability(); !available {
		writeError(w, http.StatusConflict, "UPS is unavailable on this JustVoxel variant")
		return
	}
	var request upsSharingConfig
	if !decodeJSON(w, r, &request) {
		return
	}
	upsConfigMu.Lock()
	defer upsConfigMu.Unlock()
	source, err := readUPSSource()
	if err != nil {
		writeError(w, http.StatusConflict, "UPS source configuration is invalid")
		return
	}
	if source.Mode != "local" || source.Driver == "" {
		writeError(w, http.StatusConflict, "UPS sharing requires a configured local driver")
		return
	}
	if request.Enabled {
		if net.ParseIP(request.ListenAddress) == nil || request.ListenAddress == "127.0.0.1" || request.ListenAddress == "::1" || request.ListenAddress == "0.0.0.0" || request.ListenAddress == "::" || request.ListenPort < 1 || request.ListenPort > 65535 || !validUPSCredential(request.ClientUsername, request.ClientPassword) {
			writeError(w, http.StatusBadRequest, "UPS sharing address, port, or client credentials are invalid")
			return
		}
	} else {
		request = upsSharingConfig{}
	}
	shutdown, err := readUPSShutdown()
	if err != nil {
		writeError(w, http.StatusConflict, "UPS shutdown configuration is invalid")
		return
	}
	if err := upsSystemctl(r.Context(), "disable", "--now", "nut-monitor.service"); err != nil {
		writeError(w, http.StatusServiceUnavailable, "UPS monitor could not be stopped")
		return
	}
	if err := renderUPSNative(source, shutdown, request); err == nil {
		err = writeUPSJSON(upsSharingPath, request)
	}
	if err == nil {
		err = reconcileUPSServices(r.Context(), source, shutdown)
	}
	if err != nil {
		writeError(w, http.StatusInternalServerError, "UPS sharing configuration could not be applied")
		return
	}
	if s.store != nil {
		_ = s.store.recordAuditEvent(actor, "ups_sharing_change", "local", true, fmt.Sprintf("enabled=%t", request.Enabled))
	}
	ctx, cancel := context.WithTimeout(r.Context(), 8*time.Second)
	defer cancel()
	writeJSON(w, http.StatusOK, collectUPSStatus(ctx))
}

func fillUPSNativeStatus(ctx context.Context, view *upsStatusView) {
	shutdown, shutdownErr := readUPSShutdown()
	sharing, sharingErr := readUPSSharing()
	if shutdownErr != nil || sharingErr != nil {
		view.Message = "Native UPS configuration is invalid"
		return
	}
	if (sharing.Enabled && (view.Source.Mode != "local" || view.Source.Driver == "")) || (shutdown.Enabled && (view.Source.UPSName == "" || (view.Source.Mode == "local" && view.Source.Driver == ""))) {
		view.Message = "Native UPS configuration is inconsistent"
		return
	}
	view.NUTMode = "none"
	if view.Source.Mode == "remote" {
		view.NUTMode = "netclient"
	} else if view.Source.Driver != "" {
		view.NUTMode = "standalone"
	}
	if sharing.Enabled {
		view.NUTMode = "netserver"
	}
	view.ProtectionEnabled = shutdown.Enabled
	view.ShutdownDelaySeconds = shutdown.DelaySeconds
	view.MonitorCredentialsConfigured = validUPSCredential(shutdown.MonitorUsername, shutdown.MonitorPassword)
	view.SharingEnabled = sharing.Enabled
	view.SharingListenAddress = sharing.ListenAddress
	view.SharingListenPort = sharing.ListenPort
	view.SharingCredentialsConfigured = validUPSCredential(sharing.ClientUsername, sharing.ClientPassword)
	view.MonitorServiceActive = upsServiceActive(ctx, "nut-monitor.service")
	view.ServerServiceActive = upsServiceActive(ctx, "nut-server.service")
	view.DriverServiceActive = upsServiceActive(ctx, "nut-driver.target")
}

func checkOwnedNUTFile(name string) error {
	path := filepath.Join(upsConfigDir, name)
	data, err := os.ReadFile(path)
	if errors.Is(err, os.ErrNotExist) {
		return nil
	}
	if err != nil {
		return err
	}
	if bytes.HasPrefix(data, []byte(upsOwnedHeader)) {
		return nil
	}
	active := false
	for _, line := range strings.Split(string(data), "\n") {
		line = strings.TrimSpace(line)
		if line != "" && !strings.HasPrefix(line, "#") {
			active = true
			break
		}
	}
	if !active || packagedNUTContentMatches(name, path, data) {
		return nil
	}
	return fmt.Errorf("%s contains administrator configuration", name)
}

func packagedNUTContentMatches(name, path string, data []byte) bool {
	switch name {
	case "nut.conf", "ups.conf", "upsd.conf", "upsd.users", "upsmon.conf", "upssched.conf":
	default:
		return false
	}
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	output, err := upsRPMQuery(ctx, path)
	if err != nil {
		return false
	}
	lines := strings.Split(strings.TrimSuffix(string(output), "\n"), "\n")
	if len(lines) < 3 || (lines[0] != "nut" && !strings.HasPrefix(lines[0], "nut-")) {
		return false
	}
	var digest string
	found := false
	for _, line := range lines[2:] {
		file, value, ok := strings.Cut(line, "\t")
		if !ok {
			return false
		}
		if file == path {
			if found {
				return false
			}
			found = true
			digest = value
		}
	}
	if !found || digest == "" {
		return false
	}
	var actual []byte
	switch lines[1] {
	case "8":
		sum := sha256.Sum256(data)
		actual = sum[:]
	default:
		return false
	}
	return strings.EqualFold(hex.EncodeToString(actual), digest)
}

func writeOwnedNUTFile(name, body string, mode os.FileMode) error {
	path := filepath.Join(upsConfigDir, name)
	if err := os.MkdirAll(upsConfigDir, 0o750); err != nil {
		return err
	}
	if err := upsSetNUTGroup(upsConfigDir); err != nil {
		return err
	}
	if err := os.Chmod(upsConfigDir, 0o750); err != nil {
		return err
	}
	if err := atomicWrite(path, []byte(upsOwnedHeader+body), mode); err != nil {
		return err
	}
	if mode&0o040 != 0 {
		if err := upsSetNUTGroup(path); err != nil {
			return err
		}
	}
	return nil
}

func renderUPSNative(source upsSourceConfig, shutdown upsShutdownConfig, sharing upsSharingConfig) error {
	if source.Mode != "remote" && source.Mode != "local" {
		return errors.New("UPS source mode is invalid")
	}
	if source.Mode == "remote" && sharing.Enabled {
		return errors.New("remote UPS cannot be shared")
	}
	if sharing.Enabled && source.Driver == "" {
		return errors.New("UPS sharing requires a local driver")
	}
	if shutdown.Enabled && source.Mode == "local" && source.Driver == "" {
		return errors.New("UPS protection requires a local driver")
	}
	if shutdown.Enabled && (source.UPSName == "" || !validUPSCredential(shutdown.MonitorUsername, shutdown.MonitorPassword)) {
		return errors.New("UPS protection requires a selected UPS and credentials")
	}
	if sharing.Enabled && shutdown.Enabled && sharing.ClientUsername == shutdown.MonitorUsername {
		return errors.New("UPS client and monitor users must differ")
	}
	mode := "none"
	if source.Mode == "remote" {
		mode = "netclient"
	} else if source.Driver != "" {
		mode = "standalone"
	}
	if sharing.Enabled {
		mode = "netserver"
	}
	upsConf, upsdConf, upsdUsers, upsmonConf, upsschedConf := "", "", "", "", ""
	if source.Mode == "local" && source.Driver != "" {
		upsConf = fmt.Sprintf("[%s]\n  driver = %s\n  port = %s\n", source.UPSName, source.Driver, source.DevicePort)
		upsdConf = "LISTEN 127.0.0.1 3493\n"
		if sharing.Enabled {
			upsdConf += fmt.Sprintf("LISTEN %s %d\n", sharing.ListenAddress, sharing.ListenPort)
		}
		if shutdown.Enabled {
			upsdUsers = fmt.Sprintf("[%s]\n  password = %s\n  upsmon primary\n", shutdown.MonitorUsername, shutdown.MonitorPassword)
		}
		if sharing.Enabled {
			upsdUsers += fmt.Sprintf("[%s]\n  password = %s\n  upsmon secondary\n", sharing.ClientUsername, sharing.ClientPassword)
		}
	}
	if shutdown.Enabled {
		host := "localhost"
		port := defaultNUTPort
		if source.Mode == "remote" {
			host, port = source.Host, source.Port
		}
		role := "primary"
		if source.Mode == "remote" {
			role = "secondary"
		}
		upsmonConf = fmt.Sprintf("MONITOR %s@%s 1 %s %s %s\nMINSUPPLIES 1\nSHUTDOWNCMD \"/usr/bin/sudo -n /usr/libexec/justvoxel/ups-emergency-poweroff\"\nNOTIFYCMD /usr/sbin/upssched\nNOTIFYFLAG ONBATT SYSLOG+EXEC\nNOTIFYFLAG ONLINE SYSLOG+EXEC\nNOTIFYFLAG LOWBATT SYSLOG+EXEC\nPOWERDOWNFLAG /etc/killpower\n", source.UPSName, net.JoinHostPort(host, strconv.Itoa(port)), shutdown.MonitorUsername, shutdown.MonitorPassword, role)
		timer := "justvoxel-onbatt-primary"
		if source.Mode == "remote" {
			timer = "justvoxel-onbatt-secondary"
		}
		upsschedConf = fmt.Sprintf("CMDSCRIPT /usr/libexec/justvoxel/ups-schedule-event\nPIPEFN /run/nut/upssched.pipe\nLOCKFN /run/nut/upssched.lock\nAT ONBATT * START-TIMER %s %d\nAT ONLINE * CANCEL-TIMER %s\n", timer, shutdown.DelaySeconds, timer)
	}
	files := []struct {
		name, body string
		mode       os.FileMode
	}{
		{"nut.conf", "MODE=" + mode + "\n", 0o644},
		{"ups.conf", upsConf, 0o640},
		{"upsd.conf", upsdConf, 0o640},
		{"upsd.users", upsdUsers, 0o640},
		{"upsmon.conf", upsmonConf, 0o640},
		{"upssched.conf", upsschedConf, 0o640},
	}
	for _, file := range files {
		if err := checkOwnedNUTFile(file.name); err != nil {
			return err
		}
	}
	for _, file := range files {
		if err := writeOwnedNUTFile(file.name, file.body, file.mode); err != nil {
			return err
		}
	}
	return nil
}

func reconcileUPSServices(ctx context.Context, source upsSourceConfig, shutdown upsShutdownConfig) error {
	ctx, cancel := context.WithTimeout(ctx, 40*time.Second)
	defer cancel()
	if err := upsSystemctl(ctx, "daemon-reload"); err != nil {
		return err
	}
	if err := upsSystemctl(ctx, "disable", "--now", "nut-monitor.service"); err != nil {
		return err
	}
	if err := upsSystemctl(ctx, "disable", "--now", "nut.target"); err != nil {
		return err
	}
	if err := upsSystemctl(ctx, "disable", "--now", "nut-server.service"); err != nil {
		return err
	}
	if err := upsSystemctl(ctx, "disable", "--now", "nut-driver.target"); err != nil {
		return err
	}
	if err := upsSystemctl(ctx, "disable", "--now", "nut-driver-enumerator.path"); err != nil {
		return err
	}
	if err := upsSystemctl(ctx, "disable", "--now", "nut-driver-enumerator.service"); err != nil {
		return err
	}
	if source.Mode == "remote" || source.Driver == "" {
		if err := upsSystemctl(ctx, "mask", "nut-server.service", "nut-driver.target", "nut-driver-enumerator.service", "nut-driver-enumerator.path"); err != nil {
			return err
		}
	} else {
		if err := upsSystemctl(ctx, "unmask", "nut-server.service", "nut-driver.target", "nut-driver-enumerator.service"); err != nil {
			return err
		}
		if err := upsSystemctl(ctx, "enable", "nut-driver-enumerator.service"); err != nil {
			return err
		}
		if err := upsSystemctl(ctx, "restart", "nut-driver-enumerator.service"); err != nil {
			return err
		}
		if err := upsSystemctl(ctx, "enable", "--now", "nut-server.service"); err != nil {
			return err
		}
		if err := upsSystemctl(ctx, "restart", "nut-server.service"); err != nil {
			return err
		}
	}
	if shutdown.Enabled {
		if err := upsSystemctl(ctx, "unmask", "nut-monitor.service"); err != nil {
			return err
		}
		if err := upsSystemctl(ctx, "enable", "--now", "nut-monitor.service"); err != nil {
			return err
		}
		if err := upsSystemctl(ctx, "restart", "nut-monitor.service"); err != nil {
			return err
		}
	} else {
		if err := upsSystemctl(ctx, "mask", "nut-monitor.service"); err != nil {
			return err
		}
	}
	if (source.Mode == "remote" || source.Driver == "") && !shutdown.Enabled {
		return nil
	}
	return upsSystemctl(ctx, "enable", "--now", "nut.target")
}
